FROM node:18.16.1 AS build

WORKDIR /app

COPY ./package*.json ./

COPY ./index.js ./

RUN npm run build


FROM node:18.16.1 AS final

WORKDIR /app

COPY --from=build /app/index.js ./
COPY --from=build /app/package.json ./package.json

EXPOSE 3000

CMD ["npm", "start"]

